# Generated by Django 4.2.6 on 2023-10-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PONProjectID', models.IntegerField(default=0)),
                ('MDFID', models.CharField(max_length=200)),
                ('Exchange', models.CharField(max_length=50)),
                ('PONNumber', models.CharField(max_length=15)),
            ],
        ),
    ]
