# Generated by Django 4.2.6 on 2023-10-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pon_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rob_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=25)),
            ],
        ),
    ]
