# Generated by Django 4.2.6 on 2023-10-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pon_manager', '0002_rob_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rob_table',
        ),
    ]
