# Generated by Django 4.2.6 on 2023-11-05 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pon_manager', '0003_delete_rob_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Daisy_Chain',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='Feeding_Agg',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
