# Generated by Django 4.2.6 on 2023-11-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pon_manager', '0004_table_daisy_chain_table_feeding_agg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Daisy_Chain',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Feeding_Agg',
        ),
    ]
